### ISSUE TITLE
Vendor JS / CSS

### ISSUE THREAD

**Issue by BenSto** [kjoscha/consulting#1]
lets use the vendor directory for external js and css.

**Comment by kjoscha** [comment]
correct!

**Comment by BenSto** [comment]
Maybe that would be a good job for @00Bock to learn more about rails/rails conventions and its directory structure. As a part of the IT retreat?

**Comment by kjoscha** [comment]
already done :D

**Comment by BenSto** [comment]
:rocket:  moving files is at least not that complicate

**Comment by BenSto** [comment]
external css is still imissing if I am seeing it correctly.

**Comment by BenSto** [comment]
Ok 2 commits... sorry ^^

**Comment by kjoscha** [comment]
yes, were conducted in  seperate commits
