### ISSUE TITLE
order of pages in navbar

### ISSUE THREAD

**Issue by 00Bock** [kjoscha/consulting#17]
it would make more sense to have the order
about | services | references [or currently 'work'] | contact
than the current order in the navbar. I've tried to change it myself but got stuck in rails... has it to do something with
```
          %ul.nav.navbar-nav
            - pages.each do |p|
              %li
                = link_to p, p
```

**Comment by BenSto** [comment]
To be honest, I think this is an Issue for @AnnaBreymaier because she is our in house specialist for design and even more for user interaction, which is totally mentioned here, I guess.

But to help you with your problem in general, try to understand what is happening here. There is ruby code involved, it is a for loop that loops over ```pages``` which seems to be like an array. Now you can try to manipulate arrays and so on.

**Comment by BenSto** [comment]
More precisely ```pages``` is a set.

so pages is pretty equal to ```Set.new ['work', 'about'...]``` on which you can use methods and so on.

**Comment by 00Bock** [comment]
Thanks for the reply. about, services, references, contacts... that is quite the normal order of navbars if you click through some examples. e.g. urban-software-institute.de/en/

**Comment by BenSto** [comment]
https://www.pwc.de/en/
https://www.rolandberger.com/en/

hmm I think its not that clear which is a common order. I furthermore think there is no general order that we can just follow. Maybe it really makes sense to ask @AnnaBreymaier as a specialist for exactly that cases, what she is thinking about that topic and find the best order for our needs.

**Comment by kjoscha** [comment]
Please let's discuss layout stuff in InVision. I think it is a much more practicable place for that. I know, it is hard to distinguish sometimes between code and layout, but at least please register there: https://www.invisionapp.com/

Let us know that you are registered, than we can invite you to our project :)

**Comment by BenSto** [comment]
> Please let's discuss layout stuff in InVision. I think it is a much more practicable place for that. I know, it is hard to distinguish sometimes between code and layout, but at least please register there: https://www.invisionapp.com/

Let us know that you are registered, than we can invite you to our project :)

Good Point. I'm already member of the project and have done my first comment successfully in this moment ;-)

**Comment by 00Bock** [comment]
hey, I've just signed in as 'InnoBock'. Can anyone invite me to the project please?
