### ISSUE TITLE
add purpose of repo to read me

### ISSUE THREAD

**Issue by 00Bock** [kjoscha/consulting#2]
What is the purpose of this tool/website? Is it a on-line presentation of the new data-driven services? Or is it a more specific tool like the Future Mobility DataHub?

**Comment by BenSto** [comment]
> Is it a on-line presentation of the new data-driven services?

Yes, it should be the new website for the data driven mobility consulting (name is not confirmed) as a service with the topics measuring, monitoring and analytics.
